services:
  app:
    build: ./
    container_name: posts_and_comments
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      IN_MEMORY: ${IN_MEMORY}
    networks:
      - posts_net


  postgres:
    image: postgres:16
    container_name: db_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U user" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      posts_net:
        aliases:
          - database

  #migrate:
   # image: migrate/migrate
    #container_name: migrate
    #volumes:
     # - ./migrations:/migrations
    #command: ["-path", "./migrations", "-database",  "postgres://yks:yksadm@database:5432/postgres?sslmode=disable", "up" ]
    #depends_on:
      #postgres:
        #condition: service_healthy
    #networks:
      #- posts_net



networks:
  posts_net: